export const {
	TURSO_DATABASE_URL,
	TURSO_AUTH_TOKEN,
	ACCESS_TOKEN_KEY,
	ACCESS_TOKEN_EXPIRES_IN,
	REFRESH_TOKEN_KEY,
	REFRESH_TOKEN_EXPIRES_IN,
	REFRESH_TOKEN_MAX_USES,
	PERPLEXITY_API_KEY,
	SALT_ROUNDS = 10,
	NEW_ACCOUNT_TOKENS,
} = import.meta.env
